### ISSUE TITLE
安装项目报错

### ISSUE THREAD

**Issue by luoqishuai** [howl-anderson/hanzi_char_featurizer#3]
git下载https://github.com/howl-anderson/hanzi_char_featurizer.
cd 到目录下 
python steup.py install
然后在控制台  导入包的时候 报错

`import hanzi_char_featurizer
Traceback (most recent call last):
  File "F:\ANACONDA\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-717af367fe07>", line 1, in <module>
    import hanzi_char_featurizer
  File "F:\python\PyCharm Community Edition 2017.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\ANACONDA\lib\site-packages\hanzi_char_featurizer-0.1-py3.6.egg\hanzi_char_featurizer\__init__.py", line 5, in <module>
    from hanzi_char_featurizer.featurizers.four_corner import FourCorner
  File "F:\python\PyCharm Community Edition 2017.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'hanzi_char_featurizer.featurizers'
`
看起来是项目的结构有点不正常
win 10+ python3.6.7
请问我还需要提供什么呢

**Comment by howl-anderson** [comment]
已经更新代码解决依赖丢失问题，你重新尝试一下

**Comment by luoqishuai** [comment]
嗯嗯
